[package]
name = "nix-shell-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

serde = { version = "1.0.198", features = ["derive"] }

toml = "0.8.12"
indoc = "2.0.5"
rnix = "0.12.0"
rowan = "0.15.15"
